name: Batch Evaluate Scenarios

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  batch-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run strict
        run: |
          mkdir -p reports/audit_results
          python -m audits.tools.batch_eval \
            --policy policies/tracex.policy.v2.yaml \
            --root scenarios_100_v2 \
            --mode strict \
            --out reports/audit_results
      - name: Run fallback
        run: |
          python -m audits.tools.batch_eval \
            --policy policies/tracex.policy.v2.yaml \
            --root scenarios_100_v2 \
            --mode fallback \
            --out reports/audit_results
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audit-summaries
          path: reports/audit_results/*.csv
