name: Run Audit Batch Evaluator (Inputs)

on:
  workflow_dispatch:
    inputs:
      policy_path:
        description: "Policy YAML path"
        required: true
        default: "policies/tracex.policy.v2.yaml"
      scenarios_root:
        description: "Scenarios root folder"
        required: true
        default: "scenarios_100_v2"
      mode:
        description: "Gate mode"
        type: choice
        options: [strict, fallback, demo]
        default: strict

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run evaluator
        run: |
          mkdir -p reports/audit_results
          python -m audits.tools.batch_eval \
            --policy "${{ github.event.inputs.policy_path }}" \
            --root "${{ github.event.inputs.scenarios_root }}" \
            --mode "${{ github.event.inputs.mode }}" \
            --out reports/audit_results
      - name: Upload summaries
        uses: actions/upload-artifact@v4
        with:
          name: summary-${{ github.event.inputs.mode }}
          path: reports/audit_results/summary_${{ github.event.inputs.mode }}.*
          if-no-files-found: error
